spring:
  datasource:
    url: jdbc:mysql://${{HOST}}:${{PORT}}/${{DATABASE}}
    username: ${{USER}}
    password: ${{PASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: America/Santiago
    locale: es_CL

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop